// src/api/mockData.js
// Mock data for development and testing

export const mockHospitals = [
    {
        id: 1,
        name: 'City General Hospital',
        location: 'New York, NY',
        total_ors: 12,
        active_surgeries: 5,
    },
    {
        id: 2,
        name: 'Metropolitan Medical Center',
        location: 'Los Angeles, CA',
        total_ors: 15,
        active_surgeries: 8,
    },
    {
        id: 3,
        name: 'St. Mary\'s Hospital',
        location: 'Chicago, IL',
        total_ors: 10,
        active_surgeries: 4,
    },
];

export const mockOperatingRooms = [
    {
        id: 1,
        hospital_id: 1,
        name: 'OR 1',
        type: 'Surgical Suite',
        capacity: 4,
        available: true,
        current_surgery: null,
        equipment: ['Cardiac Monitor', 'Anesthesia Machine'],
    },
    {
        id: 2,
        hospital_id: 1,
        name: 'OR 2',
        type: 'Surgical Suite',
        capacity: 4,
        available: false,
        current_surgery: 'Emergency Cardiac Surgery',
        equipment: ['Cardiac Monitor', 'Ventilator', 'ECG Machine'],
    },
    {
        id: 3,
        hospital_id: 1,
        name: 'OR 3',
        type: 'Orthopedic Suite',
        capacity: 3,
        available: true,
        current_surgery: null,
        equipment: ['X-ray Machine', 'Surgical Lights'],
    },
    {
        id: 4,
        hospital_id: 1,
        name: 'OR 4',
        type: 'ENT Suite',
        capacity: 3,
        available: true,
        current_surgery: null,
        equipment: ['Microscope', 'Endoscope'],
    },
    {
        id: 5,
        hospital_id: 1,
        name: 'OR 5',
        type: 'General Surgery',
        capacity: 4,
        available: false,
        current_surgery: 'Appendectomy',
        equipment: ['Surgical Lights', 'Cardiac Monitor'],
    },
];

export const mockStaff = [
    {
        id: 1,
        hospital_id: 1,
        name: 'Dr. John Smith',
        role: 'Surgeon',
        specialization: 'Cardiothoracic Surgery',
        available: true,
        current_surgery: null,
    },
    {
        id: 2,
        hospital_id: 1,
        name: 'Dr. Emily Johnson',
        role: 'Surgeon',
        specialization: 'Orthopedic Surgery',
        available: true,
        current_surgery: null,
    },
    {
        id: 3,
        hospital_id: 1,
        name: 'Sarah Williams',
        role: 'Anesthesiologist',
        specialization: 'General Anesthesia',
        available: false,
        current_surgery: 'Emergency Cardiac Surgery',
    },
    {
        id: 4,
        hospital_id: 1,
        name: 'Dr. Michael Brown',
        role: 'Surgeon',
        specialization: 'General Surgery',
        available: true,
        current_surgery: null,
    },
    {
        id: 5,
        hospital_id: 1,
        name: 'Jennifer Lee',
        role: 'Surgical Nurse',
        specialization: 'OR Nursing',
        available: false,
        current_surgery: 'Appendectomy',
    },
    {
        id: 6,
        hospital_id: 1,
        name: 'David Martinez',
        role: 'Surgical Nurse',
        specialization: 'OR Nursing',
        available: true,
        current_surgery: null,
    },
];

export const mockEquipment = [
    {
        id: 1,
        hospital_id: 1,
        name: 'Cardiac Monitor XR-500',
        type: 'Monitoring Device',
        is_available: true,
        sterilization_cycle_hours: 2,
        location: 'OR 1',
    },
    {
        id: 2,
        hospital_id: 1,
        name: 'Anesthesia Machine AM-200',
        type: 'Anesthesia Machine',
        is_available: false,
        sterilization_cycle_hours: 4,
        location: 'OR 2',
    },
    {
        id: 3,
        hospital_id: 1,
        name: 'Surgical Light SL-300',
        type: 'Surgical Instrument',
        is_available: true,
        sterilization_cycle_hours: 1,
        location: 'OR 3',
    },
    {
        id: 4,
        hospital_id: 1,
        name: 'Ventilator V-500',
        type: 'Life Support',
        is_available: false,
        sterilization_cycle_hours: 3,
        location: 'OR 2',
    },
    {
        id: 5,
        hospital_id: 1,
        name: 'ECG Machine EC-100',
        type: 'Monitoring Device',
        is_available: true,
        sterilization_cycle_hours: 2,
        location: 'OR 1',
    },
    {
        id: 6,
        hospital_id: 1,
        name: 'Endoscope EN-400',
        type: 'Imaging Equipment',
        is_available: true,
        sterilization_cycle_hours: 5,
        location: 'OR 4',
    },
];

export const mockSurgeryRequests = [
    {
        id: 1,
        hospital_id: 1,
        patient_name: 'John Doe',
        surgery_type: 'Cardiac Bypass',
        priority: 'EMERGENCY',
        surgeon_id: 1,
        estimated_duration_minutes: 240,
        required_equipment: ['Cardiac Monitor', 'Ventilator'],
        status: 'APPROVED',
        requested_date: '2026-02-10',
        created_at: '2026-02-10T08:30:00',
    },
    {
        id: 2,
        hospital_id: 1,
        patient_name: 'Jane Smith',
        surgery_type: 'Appendectomy',
        priority: 'URGENT',
        surgeon_id: 4,
        estimated_duration_minutes: 60,
        required_equipment: ['Surgical Light'],
        status: 'APPROVED',
        requested_date: '2026-02-10',
        created_at: '2026-02-10T09:15:00',
    },
    {
        id: 3,
        hospital_id: 1,
        patient_name: 'Robert Johnson',
        surgery_type: 'Knee Replacement',
        priority: 'NORMAL',
        surgeon_id: 2,
        estimated_duration_minutes: 120,
        required_equipment: ['X-ray Machine', 'Surgical Lights'],
        status: 'PENDING',
        requested_date: '2026-02-11',
        created_at: '2026-02-10T10:00:00',
    },
    {
        id: 4,
        hospital_id: 1,
        patient_name: 'Mary Wilson',
        surgery_type: 'Cataract Surgery',
        priority: 'NORMAL',
        surgeon_id: 1,
        estimated_duration_minutes: 45,
        required_equipment: ['Microscope'],
        status: 'PENDING',
        requested_date: '2026-02-12',
        created_at: '2026-02-10T11:00:00',
    },
    {
        id: 5,
        hospital_id: 1,
        patient_name: 'David Brown',
        surgery_type: 'Emergency C-Section',
        priority: 'EMERGENCY',
        surgeon_id: 2,
        estimated_duration_minutes: 90,
        required_equipment: ['Cardiac Monitor', 'Ventilator'],
        status: 'APPROVED',
        requested_date: '2026-02-10',
        created_at: '2026-02-10T12:00:00',
    },
];

export const mockSchedules = [
    {
        id: 1,
        hospital_id: 1,
        surgery_request_id: 1,
        operating_room_id: 2,
        surgeon_id: 1,
        anesthesiologist_id: 3,
        scheduled_start_time: '2026-02-10T10:00:00',
        scheduled_end_time: '2026-02-10T14:00:00',
        status: 'IN_PROGRESS',
        actual_start_time: '2026-02-10T10:05:00',
        actual_end_time: null,
    },
    {
        id: 2,
        hospital_id: 1,
        surgery_request_id: 2,
        operating_room_id: 5,
        surgeon_id: 4,
        anesthesiologist_id: 3,
        scheduled_start_time: '2026-02-10T14:30:00',
        scheduled_end_time: '2026-02-10T15:30:00',
        status: 'SCHEDULED',
        actual_start_time: null,
        actual_end_time: null,
    },
    {
        id: 3,
        hospital_id: 1,
        surgery_request_id: 3,
        operating_room_id: 3,
        surgeon_id: 2,
        anesthesiologist_id: null,
        scheduled_start_time: '2026-02-11T09:00:00',
        scheduled_end_time: '2026-02-11T11:00:00',
        status: 'SCHEDULED',
        actual_start_time: null,
        actual_end_time: null,
    },
];

export const mockAuditLogs = [
    {
        id: 1,
        timestamp: '2026-02-10T08:30:00',
        action: 'SURGERY_REQUESTED',
        user_id: 1,
        user_name: 'Dr. John Smith',
        resource: 'Surgery Request #1',
        details: 'Emergency cardiac bypass surgery requested',
        status: 'SUCCESS',
    },
    {
        id: 2,
        timestamp: '2026-02-10T09:00:00',
        action: 'SURGERY_APPROVED',
        user_id: 2,
        user_name: 'Admin User',
        resource: 'Surgery Request #1',
        details: 'Approved for OR scheduling',
        status: 'SUCCESS',
    },
    {
        id: 3,
        timestamp: '2026-02-10T10:05:00',
        action: 'SURGERY_STARTED',
        user_id: 3,
        user_name: 'Sarah Williams',
        resource: 'Schedule #1',
        details: 'Cardiac bypass surgery started in OR 2',
        status: 'SUCCESS',
    },
    {
        id: 4,
        timestamp: '2026-02-10T09:15:00',
        action: 'SURGERY_REQUESTED',
        user_id: 1,
        user_name: 'Dr. Michael Brown',
        resource: 'Surgery Request #2',
        details: 'Appendectomy requested',
        status: 'SUCCESS',
    },
    {
        id: 5,
        timestamp: '2026-02-10T10:00:00',
        action: 'EQUIPMENT_STERILIZED',
        user_id: 4,
        user_name: 'Nurse Jennifer Lee',
        resource: 'Equipment #1',
        details: 'Cardiac Monitor sterilization completed',
        status: 'SUCCESS',
    },
];

export const mockPriorityQueue = [
    {
        id: 1,
        position: 1,
        surgery_request_id: 1,
        patient_name: 'John Doe',
        priority: 'EMERGENCY',
        estimated_duration_minutes: 240,
        surgeon: 'Dr. John Smith',
        status: 'IN_PROGRESS',
    },
    {
        id: 2,
        position: 2,
        surgery_request_id: 5,
        patient_name: 'David Brown',
        priority: 'EMERGENCY',
        estimated_duration_minutes: 90,
        surgeon: 'Dr. Emily Johnson',
        status: 'WAITING',
    },
    {
        id: 3,
        position: 3,
        surgery_request_id: 2,
        patient_name: 'Jane Smith',
        priority: 'URGENT',
        estimated_duration_minutes: 60,
        surgeon: 'Dr. Michael Brown',
        status: 'WAITING',
    },
    {
        id: 4,
        position: 4,
        surgery_request_id: 3,
        patient_name: 'Robert Johnson',
        priority: 'NORMAL',
        estimated_duration_minutes: 120,
        surgeon: 'Dr. Emily Johnson',
        status: 'WAITING',
    },
];

export const mockDashboardStats = {
    total_surgeries_today: 3,
    total_surgeries_completed: 1,
    active_ors: 2,
    available_ors: 3,
    total_ors: 5,
    emergency_count: 2,
    urgent_count: 1,
    normal_count: 2,
    staff_available: 4,
    staff_busy: 2,
    equipment_available: 4,
    equipment_in_use: 2,
};

