# Generated by Django 6.0.2 on 2026-02-10 07:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSterilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterilized_at', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Hospital Admin'), ('room_manager', 'Operating Room Manager'), ('surgeon', 'Surgeon'), ('scheduler', 'Scheduler'), ('nurse', 'Nurse')], max_length=30)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('operating_room_type', models.CharField(choices=[('general', 'General'), ('cardiac', 'Cardiac'), ('neuro', 'Neuro'), ('ortho', 'Orthopedic')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('has_anesthesia', models.BooleanField(default=True)),
                ('has_imaging', models.BooleanField(default=False)),
                ('maintenance_until', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_on_call', models.BooleanField(default=False, help_text='Indicates if the staff is available for emergency surgeries outside of regular hours')),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('max_daily_hours', models.IntegerField(default=12)),
                ('base_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.baseuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('procedure_type', models.CharField(choices=[('general', 'General'), ('cardiac', 'Cardiac'), ('neuro', 'Neuro'), ('ortho', 'Orthopedic')], max_length=100)),
                ('complexity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('elective', 'Elective')], max_length=20)),
                ('required_specialization', models.CharField(blank=True, help_text='If the surgery requires a specific surgeon specialization', max_length=100, null=True)),
                ('anesthesia_type', models.CharField(blank=True, help_text='Type of anesthesia required (e.g., general, local, regional)', max_length=50, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('latest_allowed_time', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('preferred_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.surgeonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_priority', models.CharField(max_length=20)),
                ('wait_days', models.IntegerField(default=0)),
                ('escalated', models.BooleanField(default=False, help_text='Indicates if the surgery has been escalated due to waiting too long')),
                ('surgery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.surgeryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('surgery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surgeryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SurgerySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('bumped', 'Bumped')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operating_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operatingroom')),
                ('surgeons', models.ManyToManyField(related_name='scheduled_surgeries', to='core.surgeonprofile')),
                ('surgery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.surgeryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surgeryrequest')),
                ('affected_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surgeryschedule')),
            ],
        ),
    ]
