# Generated by Django 6.0.2 on 2026-02-10 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_surgeryrequest_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseuserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
